create database GestorEmpleados;
use GestorEmpleados;

CREATE TABLE IF NOT EXISTS TRABAJADOR(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    PUESTO VARCHAR(50) NOT NULL,
    SALARIO INT NOT NULL,
    FECHA DATE NOT NULL
);